[package]
name = "tide-demo"
version = "0.1.0"
authors = ["laixhe <laixhe@laixhe.com>"]
edition = "2018"

[dependencies]
tide = "0.16.0"
async-std = { version = "1.8.0", features = ["attributes"] }
sqlx = { version = "0.5.5", features = [ "runtime-async-std-rustls","macros","chrono","json","uuid","postgres" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15.0"
chrono = "0.4.19"
log = "0.4.14"
pretty_env_logger = "0.4.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
rustls = "0.19.1"
rust-argon2 = "0.8.3"